#! /bin/bash

static() {
  cp -r static html
}    

build() {
  agda --html --html-highlight=auto --html-dir=html Index.lagda.md
    
  for i in `find html -name "*.md"`; do
    title=$(echo $i | awk 'BEGIN{FS="[.,/]"}{print $2}')
    pandoc --standalone $i --template template.html -o html/$title.html
    rm $i
  done
    
  mv html/Index.html html/index.html
}


case $1 in
  all)
    build
    static
    ;;
  static)
    static
    ;;
  serve)
    (
      cd html
      python3 -m http.server
    )
    ;;
  *)
    echo "I don't know what to do with \"$1\""
    ;;
esac
